name: 'tuva_ccsr'
version: '0.1.0'
config-version: 2

profile: default


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"



vars:

    # Set input database, schema, and tables where your data is located
    input_database: tuva_claims_demo_full
    input_schema: core
    
    input_condition_table: condition
    input_procedure_table: procedure

    # These vars enable the wide tables - disabling will exclude wide tables from dbt runs
    wide_condition_enabled: True
    wide_procedure_enabled: True

    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "2023.1"
    prccsr_version: "2023.1"
